name: Check run action handler

on:
  check_run:
    types:
      - created
      - completed
      - requested_action

permissions: read-all

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - echo "${{ toJSON(github.event) }}"
