name: Check run action handler

on:
  check_run:
    types:
      - requested_action

permissions:
  checks: write

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - echo "${{ toJSON(github.event) }}"
