name: comment-handler

on:
  issue_comment:
    types:
      - created

jobs:
  handle-pr-comment:
    name: Handle comment on PR
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '!pr-command ') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const pull = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.issue.number
            });
            console.log(JSON.stringify(pull));
