name: comment-handler

on:
  issue_comment:
    types:
      - created

jobs:
  handle-pr-comment:
    name: Handle comment on PR
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '!pr-command ') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const {owner, repo} = context.repo;
            const {data: {head: {ref}}} = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: context.payload.issue.number
            });
            console.log(ref);
            await github.rest.actions.createWorkflowDispatch({
              owner,
              repo,
              workflow_id: "create-check-run-trigger-manually.yml",
              ref
            });
