name: Create check run

on:
  pull_request: {}

jobs:
  create-runs:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/github-script@v6
        id: test-a
        with:
          script: |
            const result = await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head_sha: context.payload.pull_request.head.sha,
              name: "test-a",
              conclusion: "neutral",
              output: {
                title: "test:a",
                summary: "test:a not started yet"
              },
              actions: [
                {
                  label: "Run test:a",
                  description: "Run test:a",
                  identifier: "test:a"
                }
              ]
            });
            return result;

      - run: echo '${{ steps.test-a.outputs.result }}'

      - uses: actions/github-script@v6
        with:
          script: |
            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head_sha: context.payload.pull_request.head.sha,
              name: "test-b",
              conclusion: "neutral",
              output: {
                title: "test:b",
                summary: "test:b not started yet"
              },
              actions: [
                {
                  label: "Run test:b",
                  description: "Run test:b",
                  identifier: "test:b"
                }
              ]
            });
