name: PR with label
run-name: PR with label ${{ github.event.label.name }}

on:
  pull_request:
    types:
      - labeled

jobs:
  run-on-pr:
    if: ${{ (github.event.label.name == 'test:a') || (github.event.label.name == 'test:b') }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - run: gh pr edit ${{ github.event.pull_request.number }} --remove-label ${{ github.event.label.name }}
      - run: echo "${{ github.event.label.name }}"
